# Generated by Django 4.0.4 on 2022-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDetailsModel',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'manager_details',
            },
        ),
    ]
