# Generated by Django 4.0.1 on 2022-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdetailsmodel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
