# Generated by Django 4.0.4 on 2022-04-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff_details',
            new_name='StaffDetails',
        ),
    ]
