# Generated by Django 4.0.4 on 2022-04-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0002_rename_staff_details_staffdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffDetails',
            new_name='StaffDetailsModel',
        ),
    ]
